# Déployer dans /etc/gdm/custom.conf
# GDM Configuration - Fedora Thin Client

[daemon]
AutomaticLoginEnable=True
AutomaticLogin=kiosk
TimedLoginEnable=False
WaylandEnable=false

[security]
DisallowTCP=true

[xdmcp]

[chooser]

[debug]
